# -*- coding: utf8 -*-

manual_matches = {'evo':{
'Aiguette':"L'Ayguette",
'Alignon (du Haut Tarn)':"L'Alignon",
"Ebron":"L'Ébron",
"Alzeau":"La Rougeanne",
"Ance du Sud":"L'Ance",
"Alpe Basso":"Rio del Basso",
"Behine":"La Béhine",
"Besorgues":"La Bésorgues",
"boralde d'Espalion":"Boralde Flaujaguèse",
"Borrey":"L'Oignin",
"Bramabiau":"Le Bonheur",
"Brezou":"Le Brézou",
"Bés":"Le Bès",
"Brézillou":"Le Brézihou",
"Candessoubre":"Ruisseau de Candesoubre",
"Canut de Renac":"Le Canut",
"Colagne (Haute)":"La Colagne",
"Combe Jean":"Ruisseau de Combejean",
"Corrèze de Pradines":"La Petite Corrèze",
"COSCIONE":"Le Chiuvone",
"Courbiere":"Ruisseau de la Courbière",
"Couze de valbeleix":"La Couze du Valbeleix",
"Crueize (ou Gorges de l'Enfer)":"La Crueize",
"Dordogne (basse)":"La Dordogne",
"Elorn":"L'Élorn",
"Escaumel":"Ruisseau d'Escalmels",
"Espezonette":"L'Espézonnette",
"Rivière d'Etel":"Rivière d'Étel",
"Fium Grosso":["Rivière de Guagno","Liamone"],
"Fium Orbo":"U Fium Orbu",
"Foron de Sciez":"Le Foron",
"Foron de Taninges":"Le Foron",
"Gardon de St Martin de Lansuscle":"Le Gardon",
"Gardon sans nom":"Le Gardon",
"Gave d'Arrens":"Le Gave d'Azun",
"Gave d'Aydius":"Le Gave d'Aydius ou Gabarret",
"Gave de Cauteret":"Gave de Cauterets",
"Gave de Larrau-Saison":"Zürkaïtzegiko Erreka",
"Gave de Sainte Engrâce":"Uhaïtza",
"Gave du Lourdios":"Le Gave de Lourdios",
"Glueyre":"La Gluèyre",
"Gottero":"Gottera",
"Gourdouze":"Ruisseau de Gourdouse",
"Grande Blourde":"La Blourde",
"Grande Eyvia":"Grand Eyvia",
"Grande Nive":"La Nive",
"Gravone":"La Gravona",
"Guichard":"Ghicciard",
"Heas (gave d')":"Gave de Héas",
"hyeres":"L'Hyères",
"Hérault de St Guilhem":"L'Hérault",
"Leguer":"Le Léguer",
"Leyre":"L'Eyre",
"Lez (d'Ariège)":"Le Lez",
"Lignon de l'Ardèche":"Le Lignon",
"Lignon du Forez":"Le Lignon",
"Lignon du Velay":"Le Lignon",
"Lizola":"Ruisseau de Zoicu",
"Lot (Haut)":"Le Lot",
"Malzac":"Ruisseau de Malezac",
"Mayenne (haute)":"La Mayenne",
},
'rivermap':{},'ckfiumi':{"Guichard":"Ghicciard"}}
