# -*- coding: utf8 -*-

manual_matches = {'evo':{
'Aiguette':"L'Ayguette",
'Alignon (du Haut Tarn)':"L'Alignon",
"Ebron":"L'Ébron",
"Alzeau":"La Rougeanne",
"Ance du Sud":"L'Ance",
"Alpe Basso":"Rio del Basso",
"Behine":"La Béhine",
"Besorgues":"La Bésorgues",
"boralde d'Espalion":"Boralde Flaujaguèse",
"Borrey":"L'Oignin",
"Bramabiau":"Le Bonheur",
"Brezou":"Le Brézou",
"Bés":"Le Bès",
"Brézillou":"Le Brézihou",
"Candessoubre":"Ruisseau de Candesoubre",
"Canut de Renac":"Le Canut",
"Colagne (Haute)":"La Colagne",
"Combe Jean":"Ruisseau de Combejean",
"Corrèze de Pradines":"La Petite Corrèze",
"COSCIONE":"Le Chiuvone",
"Courbiere":"Ruisseau de la Courbière",
"Couze de valbeleix":"La Couze du Valbeleix",
"Crueize (ou Gorges de l'Enfer)":"La Crueize",
"Dordogne (basse)":"La Dordogne",
"Elorn":"L'Élorn",
"Escaumel":"Ruisseau d'Escalmels",
"Espezonette":"L'Espézonnette",
"Rivière d'Etel":"Rivière d'Étel",
},
'rivermap':{},'ckfiumi':{}}
