# -*- coding: utf8 -*-

manual_matches = {'evo':{
"Agout":"L'Agoût",
'Aiguette':"L'Ayguette",
'Alignon (du Haut Tarn)':"L'Alignon",
"Ebron":"L'Ébron",
"Alpe Basso":"Rio del Basso",
"Alzeau":"La Rougeanne",
"Alzou (Aveyron (12))":"L'Alzou",
"Alzou (Lot (46))":"L'Alzou",
"Ance du Sud":"L'Ance",
"Ance du nord":"L'Ance",
"Ardèche (basse)":"L'Ardèche",
"Ardèche (haute)":"L'Ardèche",
"Ariège (Haute)":"L'Ariège",
"Behine":"La Béhine",
"Besorgues":"La Bésorgues",
"boralde d'Espalion":"Boralde Flaujaguèse",
"Borne (Ardèche (07))":"La Borne",
"Borne (Haute Savoie (74))":"La Borne",
"Borne (Haute-Loire (43))":"La Borne",
"Borrey":"L'Oignin",
"Bramabiau":"Le Bonheur",
"Brezou":"Le Brézou",
"Bés":"Le Bès",
"Brézillou":"Le Brézihou",
"Candessoubre":"Ruisseau de Candesoubre",
"Canut de Renac":"Le Canut",
"Colagne (Haute)":"La Colagne",
"Combe Jean":"Ruisseau de Combejean",
"Corrèze de Pradines":"La Petite Corrèze",
"COSCIONE":"Le Chiuvone",
"Courbiere":"Ruisseau de la Courbière",
"Couze de valbeleix":"La Couze du Valbeleix",
"Crueize (ou Gorges de l'Enfer)":"La Crueize",
"Dordogne (basse)":"La Dordogne",
"Drac (Provence-Alpes-Côte d'Azur)":"Le Drac",
"Drac (Rhône-Alpes)":"Le Drac",
"Elorn":"L'Élorn",
"Escaumel":"Ruisseau d'Escalmels",
"Espezonette":"L'Espézonnette",
"Rivière d'Etel":"Rivière d'Étel",
"Fium Alto":"Le Fium'Alto",
"Fium Grosso":["Rivière de Guagno","Liamone"],
"Fium Orbo":"U Fium Orbu",
"Foron de Sciez":"Le Foron",
"Foron de Taninges":"Le Foron",
"Garonne - Les Roches":"La Garonne",
"Gardon de St Martin de Lansuscle":"Le Gardon",
"Gardon sans nom":"Le Gardon",
"Gave d'Arrens":"Le Gave d'Azun",
"Gave d'Aydius":"Le Gave d'Aydius ou Gabarret",
"Gave de Cauteret":"Gave de Cauterets",
"Gave de Larrau-Saison":"Zürkaïtzegiko Erreka",
"Gave de Sainte Engrâce":"Uhaïtza",
"Gave du Lourdios":"Le Gave de Lourdios",
"Glueyre":"La Gluèyre",
"Gottero":"Gottera",
"Gourdouze":"Ruisseau de Gourdouse",
"Grande  Blourde":"La Blourde",
"Grande Eyvia":"Grand Eyvia",
"Grande Nive":"La Nive",
"Gravone":"La Gravona",
"Guichard":"Ghicciard",
"Heas (gave d')":"Gave de Héas",
"hyeres":"L'Hyères",
"Hyères (Bretagne)":"L'Hyères",
"Hyères (Rhône-Alpes)":"L'Hyères",
"Hérault de St Guilhem":"L'Hérault",
"Leguer":"Le Léguer",
"Leyre":"L'Eyre",
"Lez (d'Ariège)":"Le Lez",
"LEZ":"Le Lez", # de montpellier
"Lignon de l'Ardèche":"Le Lignon",
"Lignon du Forez":"Le Lignon",
"Lignon du Velay":"Le Lignon",
"Lizola":"Ruisseau de Zoicu",
"Lot (Haut)":"Le Lot",
"Lot (Languedoc-Roussillon)":"Le Lot",
"Lot (Midi-Pyrénées)":"Le Lot",
"Loue (Aquitaine)":"La Loue",
"Loue (Franche-Comté)":"La Loue",
"Lys (Limousin)":"Le Lys",
"Lys (Nord Pas de Calais)":"La Lys",
"Malzac":"Ruisseau de Malezac",
"Mayenne (haute)":"La Mayenne",
"mont giroux (mayenne)":"La Mayenne",
"Mosellotte":"La Moselotte",
"Mouss":"Ruisseau du Mousse",
"Nive d'Estérençuby":"La Nive",
"Ouvèze de l'ardèche":"L'Ouvèze",
"Ouvèze des Baronnies":"L'Ouvèze",
"Portet sur Garonne":"La Garonne",
"Raddon de Fresse":"Le Raddon",
"Rhône (entier)":"Le Rhône",
"Rieu Massel":"Le Rieumassel",
"Rieumalet":"Le Rieumal",
"ruisseau de Porte Etoupe":"Ruisseau de Porte-Étoupe",
"Rushia":"Ruschia",
"Sagone":["Ruisseau de Balgona","Ruisseau de Juane Rangu","Rivière de Sagone"],
"Saint Bonnette":"La Saint-Bonnette",
"Salat (Haut)":"Le Salat",
"Seille (Haute)":"La Seille",
#"La Serène de Sanvensa ":"La Serène de Sanvensa",
"sevre nantaise (Haute Sèvre )":"La Sèvre Nantaise",
"Sioule (Basse)":"La Sioule",
"Sorgues d'Entraigues":["La Sorgue d'Entraigues","La Sorgue"],
"Sorgues de Velleron":"La Sorgue de Velleron",
"Sûre":"La Sure",
"Tapoul":"Trépalous",
"Thon":"Le Ton",
"Trebbia/Aveto":["Torrente Aveto","Trebbia"],
"Truyére":"La Truyère",
"Urthier":"Torrent d'Urtier",
"Usses":"Les Usses",
"Valeine (Cascades de Murel)":"La Valeine",
"Varenne (Orne (61))":"La Varenne",
"Varenne (Seine-Maritime (76))":"La Varenne",
"Verghellu":"Ruisseau de Verjello",
"Versoyen Torrent des Glaciers":"Torrent des Glaciers",
"Vial":"Le Lignon",
"Viaur (Haut)":"Le Viaur",
"Vizezy":"Le Vizery",
"Voueze":"La Voueize",
"Vézère corrézienne":"La Vézère",
},
'rivermap':{},'ckfiumi':{"Guichard":"Ghicciard"}}
